version: '3.8'
services:
  db:
    image: postgres:13
    container_name: trading_db
    environment:
      POSTGRES_USER: YOUR_DB_USERNAME
      POSTGRES_PASSWORD: YOUR_DB_PASSWORD
      POSTGRES_DB: trading_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: trading_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/trading_db
      - SPRING_DATASOURCE_USERNAME=YOUR_DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=YOUR_DB_PASSWORD
      - KITE_API_KEY=${KITE_API_KEY}
      - KITE_API_SECRET=${KITE_API_SECRET}
      - KITE_REQUEST_TOKEN=${KITE_REQUEST_TOKEN}

volumes:
  postgres_data: