package com.example.tradingapp.service;

import com.example.tradingapp.model.Order;
import com.example.tradingapp.model.Ticker;
import com.example.tradingapp.strategy.TradingStrategy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
public class TradingEngine {

    private static final Logger logger = LoggerFactory.getLogger(TradingEngine.class);

    private final StrategyService strategyService;
    private final KiteConnectService kiteConnectService;
    private String activeStrategyName = "InvertedSuperTrendStrategy"; // Default strategy

    public TradingEngine(StrategyService strategyService, KiteConnectService kiteConnectService) {
        this.strategyService = strategyService;
        this.kiteConnectService = kiteConnectService;
    }

    @Scheduled(fixedRate = 60000) // Run every minute
    public void runScheduledTask() {
        logger.info("Trading engine is running...");

        Optional<TradingStrategy> strategyOptional = strategyService.getStrategy(activeStrategyName);
        if (strategyOptional.isEmpty()) {
            logger.warn("No active strategy found with name: {}", activeStrategyName);
            return;
        }

        TradingStrategy strategy = strategyOptional.get();
        logger.info("Executing strategy: {}", strategy.getName());

        // =======================================================================================
        // Fetch Live Market Data
        // In a real application, you would fetch live market data from Kite Connect here.
        // For demonstration purposes, we are generating mock data.
        // =======================================================================================
        logger.info("Generating mock tickers for demonstration...");
        List<Ticker> tickers = createMockTickers();

        Order signal = strategy.generateSignal(tickers);

        if (signal != null) {
            logger.info("Signal generated: {} {} {} at {}", signal.getTransactionType(), signal.getQuantity(), signal.getSymbol(), signal.getPrice());
            // Here you would place the order using the KiteConnectService
            // kiteConnectService.placeOrder(signal);
        } else {
            logger.info("No signal generated by strategy.");
        }
    }

    public void setActiveStrategy(String strategyName) {
        this.activeStrategyName = strategyName;
    }

    private List<Ticker> createMockTickers() {
        List<Ticker> tickers = new ArrayList<>();
        double price = 100.0;
        LocalDateTime timestamp = LocalDateTime.now().minusMinutes(30);

        // Generate 15 tickers to establish a trend
        for (int i = 0; i < 15; i++) {
            price -= 0.5;
            tickers.add(createTicker("INFY", price, timestamp.plusMinutes(i)));
        }

        // Generate a trend reversal
        for (int i = 0; i < 10; i++) {
            price += 1.0;
            tickers.add(createTicker("INFY", price, timestamp.plusMinutes(15 + i)));
        }

        return tickers;
    }

    private Ticker createTicker(String symbol, double close, LocalDateTime timestamp) {
        Ticker ticker = new Ticker();
        ticker.setSymbol(symbol);
        ticker.setOpen(close - 1);
        ticker.setHigh(close + 1);
        ticker.setLow(close - 2);
        ticker.setClose(close);
        ticker.setVolume(100000);
        ticker.setTimestamp(timestamp);
        return ticker;
    }
}